# Generated by Django 3.0.5 on 2020-04-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brownbags', '0002_auto_20200415_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category_sel',
            field=models.IntegerField(choices=[(0, 'その他'), (1, 'テイクアウト'), (2, 'デリバリー'), (3, 'テイクアウト&デリバリー'), (-1, '指定なし')], default=-1, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='expired_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='brownbags.Shop', verbose_name='店舗'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='addr',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='店舗住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='addr_sel',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='承認'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='allergy_note',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='アレルギー対応'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='area_sel',
            field=models.IntegerField(choices=[(0, 'その他'), (1, '武蔵小杉・新丸子・元住吉'), (2, '武蔵新城・武蔵中原'), (3, '溝の口・梶ヶ谷・鷺沼'), (4, '登戸・稲田堤'), (5, '川崎・平間'), (6, '百合ヶ丘・新百合ヶ丘'), (7, '川崎市川崎区'), (8, '川崎市幸区'), (9, '川崎市中原区'), (10, '川崎市高津区'), (11, '川崎市宮前区'), (12, '川崎市多摩区'), (13, '川崎市麻生区'), (14, '横浜市青葉区'), (15, '横浜市都筑区'), (16, '横浜市港北区'), (17, '横浜市鶴見区'), (18, '横浜市緑区'), (19, '横浜市神奈川区'), (20, '横浜市瀬谷区'), (21, '横浜市旭区'), (22, '横浜市保土ケ谷区'), (23, '横浜市南区'), (24, '横浜市西区'), (25, '横浜市中区'), (26, '横浜市泉区'), (27, '横浜市戸塚区'), (28, '横浜市港南区'), (29, '横浜市磯子区'), (30, '横浜市栄区'), (31, '横浜市金沢区'), (-1, '地域の指定なし')], default=-1, verbose_name='店舗の地域'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='closes_shop_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='休止・閉店'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='covid19_note',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='コロナ対策'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_demaekan',
            field=models.BooleanField(default=False, verbose_name='出前館'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_note',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='デリバリー対応'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_other',
            field=models.BooleanField(default=False, verbose_name='デリバリー・その他'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_own',
            field=models.BooleanField(default=False, verbose_name='自店で配達'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='delivery_ubereats',
            field=models.BooleanField(default=False, verbose_name='UberEats（ウーバーイーツ）'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='店舗概要'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='diet_note',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='ベジタリアン対応'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='expired_shop_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='無効'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='genre_sel',
            field=models.IntegerField(choices=[(0, 'その他'), (1, 'お弁当・お惣菜'), (2, '中華料理'), (3, '和食・日本料理・お寿司'), (4, 'ピザ・パスタ'), (5, '洋食・西洋料理・とんかつ'), (6, '居酒屋・ダイニングバー・焼鳥'), (7, 'アジア・エスニック・カレー'), (8, 'ステーキ・ハンバーグ・焼肉・ホルモン'), (9, '創作料理・無国籍料理'), (10, 'ラーメン'), (11, 'カフェ・喫茶店'), (12, 'バー・パブ・ラウンジ'), (13, 'パン・サンドイッチ'), (14, 'スイーツ'), (15, 'スーパーマーケット・コンビニエンスストア'), (-1, 'ジャンルなし')], default=-1, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='緯度(latitude)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='line',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='LINE'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='経度(longitude)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='mail',
            field=models.CharField(default=None, max_length=512, null=True, verbose_name='メール'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(default=None, max_length=512, null=True, unique=True, verbose_name='店名'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='note',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='留意事項'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open_day',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='定休日・営業時間'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='payment_card',
            field=models.BooleanField(default=False, verbose_name='クレジットカード'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='payment_cash',
            field=models.BooleanField(default=False, verbose_name='現金'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='payment_emoney',
            field=models.BooleanField(default=False, verbose_name='電子マネー'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='payment_note',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='支払いノート'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='payment_qr',
            field=models.BooleanField(default=False, verbose_name='QRコード決済'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sns_other',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='SNS、他サイト'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='soldout_delivery_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='デリバリー売り切れ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='soldout_takeaway_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='テイクアウト売り切れ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='takeaway_menu',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='テイクアウトメニュー'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='takeaway_note',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='テイクアウト対応'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='takeaway_sel',
            field=models.IntegerField(choices=[(0, 'その他'), (1, '対応している'), (2, '対応してない'), (3, '準備中'), (-1, '指定なし')], default=-1, verbose_name='テイクアウト'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='transportation',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='交通手段'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.IntegerField(choices=[(0, 'オーナー'), (1, 'ユーザー'), (-1, '---')], default=-1, verbose_name='タイプ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='ホームページ'),
        ),
    ]
