# Generated by Django 3.0.5 on 2020-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brownbags', '0003_auto_20200418_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='group_sel',
            field=models.IntegerField(choices=[(0, 'その他'), (1, '武蔵小杉カレーフェスティバル'), (-1, '指定なし')], default=-1, verbose_name='グループ'),
        ),
    ]
