# Generated by Django 3.0.5 on 2020-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brownbags', '0004_shop_group_sel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image_data_class',
            field=models.IntegerField(choices=[(0, 'その他'), (1, '店舗'), (2, 'テイクアウト'), (3, '店舗&テイクアウト'), (-1, '---')], default=-1, verbose_name='クラス'),
        ),
    ]
