# Generated by Django 3.0.5 on 2020-04-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brownbags', '0005_auto_20200430_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='group_sel',
            field=models.IntegerField(choices=[(0, 'その他'), (1, '武蔵小杉カレーフェスティバル'), (2, '川崎市内テイクアウト＆デリバリー実施店舗リスト'), (3, 'テイクアウト＆デリバリー横浜'), (-1, '指定なし')], default=-1, verbose_name='グループ'),
        ),
    ]
